In [7]:
import numpy as np
import pandas as pd

# Series en pandas

In [8]:
serie_vacia = pd.Series() 
print(serie_vacia)
#Output: Series([], dtype: object)

# Ahora creamos un array
vector = np.array(range(1,10))
print(vector)
#Output: [1 2 3 4 5 6 7 8 9]
# A continuación creamos la serie a partir del array creado anteriormente
serie = pd.Series(vector)
print(serie)

Series([], dtype: object)
[1 2 3 4 5 6 7 8 9]
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [9]:
#Definimos una lista
lista_1 = [4,8,15,16,23,42]

#Creamos la Serie
serie_lista_1 = pd.Series(lista_1)
print(serie_lista_1)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In [10]:
#Definimos un diccionario
country_continent = {'Spain':'Europe',
                     'USA':'North America',
                     'Australia':'Oceania',
                     'Argentina':'South America'}
#Creamos una serie a partir del diccionario
serie_diccionario = pd.Series(country_continent)
print(serie_diccionario)

Spain               Europe
USA          North America
Australia          Oceania
Argentina    South America
dtype: str

In [11]:
#Recordemos nuestro diccionario.
print(f'La serie con la que vamos a trabajar es:\n{serie_diccionario}')
print("---------------------------")
#Ahora vamos a ir utilizando cada método de indexación
print(f'El valor de la serie en la posición 0 es: {serie_diccionario.iloc[1]}')
print("---------------------------")

La serie con la que vamos a trabajar es:
Spain               Europe
USA          North America
Australia          Oceania
Argentina    South America
dtype: str
---------------------------
El valor de la serie en la posición 0 es: North America
---------------------------

In [12]:
#Recordemos nuestro diccionario.
print(f'La serie con la que vamos a trabajar es:\n{serie_diccionario}')
print("---------------------------")
print(f'El valor de la serie con etiqueta "USA" es: {serie_diccionario["Spain"]}')
print("---------------------------")

La serie con la que vamos a trabajar es:
Spain               Europe
USA          North America
Australia          Oceania
Argentina    South America
dtype: str
---------------------------
El valor de la serie con etiqueta "USA" es: Europe
---------------------------

In [13]:
#Recordemos nuestro diccionario.
print(f'La serie con la que vamos a trabajar es:\n{serie_diccionario}')
print("---------------------------")
print(f'Los valores de la serie en las posiciones 1 a 2 son: \n{serie_diccionario[1:3]}')

La serie con la que vamos a trabajar es:
Spain               Europe
USA          North America
Australia          Oceania
Argentina    South America
dtype: str
---------------------------
Los valores de la serie en las posiciones 1 a 2 son:
USA          North America
Australia          Oceania
dtype: str

In [14]:
#Recordemos nuestro diccionario.
print(f'La serie con la que vamos a trabajar es:\n{serie_diccionario}')
print("---------------------------")
lista_indices = [1,3]
print(f'Los valores de la serie en las posiciones 1 y 3 son:\n{serie_diccionario.iloc[lista_indices]}')

La serie con la que vamos a trabajar es:
Spain               Europe
USA          North America
Australia          Oceania
Argentina    South America
dtype: str
---------------------------
Los valores de la serie en las posiciones 1 y 3 son:
USA          North America
Argentina    South America
dtype: str

# DataFrames en pandas

In [15]:
import pandas as pd
import numpy as np

pd.DataFrame(data=None, index=None, columns=None)

Empty DataFrame
Columns: []
Index: []

In [16]:
#Creación a partir de un diccionario
diccionario = {"carrera": ["bioquímica", "derecho", "bellas artes"],
               "nota de corte": [12.730, 7.442, 9.906], 
               "facultad": ["Ciencias Químicas", "Derecho", "Bellas Artes"],
               "plazas": [100, 300, 250]}
#Una vez creado el diccionario generamos el DataFrame indicando el índice
df_ucm = pd.DataFrame(diccionario, index = ["Ciencias", "Ciencias Sociales", "Artes y Humanidades"])
df_ucm

                          carrera  nota de corte           facultad  plazas
Ciencias               bioquímica         12.730  Ciencias Químicas     100
Ciencias Sociales         derecho          7.442            Derecho     300
Artes y Humanidades  bellas artes          9.906       Bellas Artes     250

In [17]:
#Creación a partir de un array
array = np.random.randint(1,90, (2,3))
#Generamos el DataFrame a partir del DataFrame
df_años = pd.DataFrame(array, columns = [2012, 2013, 2014])
df_años

   2012  2013  2014
0    41    33    80
1    25    75    46

In [18]:
lista_notas = [6,7.5,8]
#DataFrame generado a partir de una lista.
df_notas = pd.DataFrame(lista_notas)
print(df_notas)

df_notas_tit = pd.DataFrame(lista_notas,columns=['Notas'])
print(df_notas_tit)

     0
0  6.0
1  7.5
2  8.0
   Notas
0    6.0
1    7.5
2    8.0

In [19]:
lista_examenes = ['control','parcial','final']
lista_notas = [6,7.5,8]
#Creamos el DataFrame a partir de una lista de listas.
df_notas_examenes = pd.DataFrame([lista_examenes,lista_notas])
df_notas_examenes.T #El .T es para trasponer el DataFrame, es decir, cambiar las filas por columnas

         0    1
0  control    6
1  parcial  7.5
2    final    8

# Apertura de archivos en Pandas

- archivos de CSV o TXT
df_csv = pd.read_csv(ruta_al_fichero , 
                     sep = ',', 
                     header = 'infer', 
                     index_col = None)

- archivos de excel
df_excel = pd.read_excel(ruta_al_fichero, 
                         sheet_name = 0, 
                         header = 0, 
                         index_col = None)

- archivos de JSON
df_json = pd.read_json(ruta_al_fichero, 
                       orient = None, 
                       typ = 'frame')

In [20]:
df_csv = pd.read_csv('./data/INEbase_GraduadosUniversitarios.csv' , 
                     sep = ';', 
                     header = 'infer', 
                     index_col = None)

df_csv

,Sexo,Edad,Familia profesional,Total
0,Ambos sexos,Total,Total que han realizado Ciclos formativos o en...,100
1,Ambos sexos,Total,Agraria,"1,2"
2,Ambos sexos,Total,Industrias alimentarias,"0,6"
3,Ambos sexos,Total,Química,1
4,Ambos sexos,Total,Imagen personal,"3,4"
...,...,...,...,...
199,Mujeres,De 35 y más años,Servicios socioculturales y a la comunidad,"3,7"
200,Mujeres,De 35 y más años,Hostelería y turismo,2
201,Mujeres,De 35 y más años,Actividades físicas y deportivas,"4,6"
202,Mujeres,De 35 y más años,Enseñanzas artísticas profesionales,"10,3"
203,Mujeres,De 35 y más años,Otras familias profesionales,"3,7"

In [21]:
df_excel = pd.read_excel('./data/INEbase_GraduadosUniversitarios.xlsx', skiprows=6)

df_excel

c:\Users\ecalderonf\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,,Total que han realizado Ciclos formativos o enseñanzas deportivas de grado medio o Enseñanzas artísticas profesionales,Agraria,Industrias alimentarias,Química,Imagen personal,Sanidad,Fabricación mecánica,Electricidad y electrónica,Transporte y mantenimiento de vehículos,Imagen y sonido,Administración y gestión,Comercio y marketing,Servicios socioculturales y a la comunidad,Hostelería y turismo,Actividades físicas y deportivas,Enseñanzas artísticas profesionales,Otras familias profesionales
0,Ambos sexos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,100.0,1.2,0.6,1.0,3.4,21.2,1.4,7.0,1.5,1.1,18.3,3.0,4.6,2.6,11.9,21.7,3.8
2,Menores de 30 años,100.0,0.1,0.9,0.0,1.4,10.5,0.3,0.2,0.2,0.2,4.1,1.2,2.6,2.0,24.3,51.6,0.8
3,De 30 a 34 años,100.0,1.5,0.3,1.2,5.2,17.0,1.0,5.4,2.7,1.6,21.1,3.5,8.5,3.0,9.8,16.1,3.9
4,De 35 y más años,100.0,1.7,0.6,1.4,2.9,31.9,2.4,12.7,1.2,1.3,24.6,3.8,2.2,2.6,6.1,8.1,5.5
5,Hombres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Total,100.0,1.5,0.4,0.7,0.3,10.1,3.3,17.1,3.0,1.7,14.4,2.8,1.3,4.0,21.5,16.7,5.8
7,Menores de 30 años,100.0,0.0,0.3,0.0,0.9,6.7,0.0,0.4,0.6,0.4,0.0,0.0,0.0,2.7,46.1,41.7,0.3
8,De 30 a 34 años,100.0,2.5,0.7,0.6,0.0,7.1,2.5,13.6,5.3,3.0,14.9,2.5,3.5,5.3,19.4,13.2,6.8
9,De 35 y más años,100.0,1.4,0.2,1.1,0.1,14.9,6.1,30.6,2.3,1.2,22.6,4.7,0.0,3.5,8.4,4.9,8.2
10,Mujeres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Total,100.0,1.0,0.7,1.2,5.4,28.5,0.1,0.3,0.5,0.8,20.9,3.2,6.8,1.7,5.6,24.9,2.4
12,Menores de 30 años,100.0,0.2,1.3,0.0,1.7,12.8,0.4,0.0,0.0,0.0,6.8,2.0,4.3,1.5,10.5,57.8,1.1
13,De 30 a 34 años,100.0,0.8,0.0,1.6,8.6,23.6,0.0,0.0,0.9,0.7,25.2,4.1,11.9,1.4,3.4,18.1,2.0
14,De 35 y más años,100.0,1.8,0.9,1.5,4.8,43.1,0.0,0.8,0.5,1.4,25.9,3.1,3.7,2.0,4.6,10.3,3.7
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1) Los titulados en más de una titulación se h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Fuente:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Instituto Nacional de Estadística,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
import sys
print(sys.executable)

c:\Users\ecalderonf\AppData\Local\Programs\Python\Python312\python.exe

In [23]:
df_json = pd.read_json('./data/INEbase_GraduadosUniversitarios.json')

df_json

,Nombre,MetaData,Data
0,"Ambos sexos, Total, Total que han realizado Ci...","[{'T3_Variable': 'sexo', 'Nombre': 'Ambos sexo...",[{'Valor': 100.0}]
1,"Ambos sexos, Total, Agraria","[{'T3_Variable': 'sexo', 'Nombre': 'Ambos sexo...",[{'Valor': 1.2}]
2,"Ambos sexos, Total, Industrias alimentarias","[{'T3_Variable': 'sexo', 'Nombre': 'Ambos sexo...",[{'Valor': 0.6000000000000001}]
3,"Ambos sexos, Total, Química","[{'T3_Variable': 'sexo', 'Nombre': 'Ambos sexo...",[{'Valor': 1.0}]
4,"Ambos sexos, Total, Imagen personal","[{'T3_Variable': 'sexo', 'Nombre': 'Ambos sexo...",[{'Valor': 3.4}]
...,...,...,...
199,"Mujeres, De 35 y más años, Servicios sociocult...","[{'T3_Variable': 'sexo', 'Nombre': 'Mujeres', ...",[{'Valor': 3.7}]
200,"Mujeres, De 35 y más años, Hostelería y turismo","[{'T3_Variable': 'sexo', 'Nombre': 'Mujeres', ...",[{'Valor': 2.0}]
201,"Mujeres, De 35 y más años, Actividades físicas...","[{'T3_Variable': 'sexo', 'Nombre': 'Mujeres', ...",[{'Valor': 4.6}]
202,"Mujeres, De 35 y más años, Enseñanzas artístic...","[{'T3_Variable': 'sexo', 'Nombre': 'Mujeres', ...",[{'Valor': 10.3}]
203,"Mujeres, De 35 y más años, Otras familias prof...","[{'T3_Variable': 'sexo', 'Nombre': 'Mujeres', ...",[{'Valor': 3.7}]

In [24]:
df_json = pd.read_json('./data/INEbase_GraduadosUniversitarios.json')

df_limpio = pd.DataFrame({
    "Nombre": df_json["Nombre"],
    "Valor": df_json["Data"].apply(lambda x: x[0]["Valor"])
})

df_limpio

                                                Nombre  Valor
0    Ambos sexos, Total, Total que han realizado Ci...  100.0
1                          Ambos sexos, Total, Agraria    1.2
2          Ambos sexos, Total, Industrias alimentarias    0.6
3                          Ambos sexos, Total, Química    1.0
4                  Ambos sexos, Total, Imagen personal    3.4
..                                                 ...    ...
199  Mujeres, De 35 y más años, Servicios sociocult...    3.7
200    Mujeres, De 35 y más años, Hostelería y turismo    2.0
201  Mujeres, De 35 y más años, Actividades físicas...    4.6
202  Mujeres, De 35 y más años, Enseñanzas artístic...   10.3
203  Mujeres, De 35 y más años, Otras familias prof...    3.7

[204 rows x 2 columns]

In [25]:
pd.set_option('display.max_columns', None)

df_csv_universidades = pd.read_csv('./data/DatosPandasUniversidades.csv', index_col = 2)

df_csv_universidades

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
University of Nottingham,100,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States
Pontificia Universidad CatÃ³lica de Chile (UC),102,103,59.9,92.9,99.5,20.6,11.6,16.4,3.5,56.8,76.3,91.3,0.0,Chile
The University of Sheffield,103,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom
Uppsala University,104,105,59.4,62.7,30.5,47.7,45.6,98.3,82.4,95.5,58.2,99.4,0.0,Sweden

In [26]:
df_csv_universidades.head()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States

In [27]:
df_csv_universidades.tail()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
University of Nottingham,100,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States
Pontificia Universidad CatÃ³lica de Chile (UC),102,103,59.9,92.9,99.5,20.6,11.6,16.4,3.5,56.8,76.3,91.3,0.0,Chile
The University of Sheffield,103,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom
Uppsala University,104,105,59.4,62.7,30.5,47.7,45.6,98.3,82.4,95.5,58.2,99.4,0.0,Sweden

In [28]:
df_csv_universidades.sample(3)

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
UniversitÃ© PSL,23,24,85.8,73.7,97.0,99.3,95.7,69.2,72.7,100.0,60.8,80.4,4.8,France
McGill University,30,30,83.7,93.7,87.6,64.0,62.1,88.9,93.3,86.2,92.5,94.2,0.0,NaN
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States

In [29]:
print(df_csv_universidades.shape)

print(df_csv_universidades.size)

print(df_csv_universidades.columns)

print(df_csv_universidades.info())

print(df_csv_universidades.dtypes)

# Esta linea muestra las columnas de tupo Object
print(df_csv_universidades.select_dtypes(include = 'O'))

(105, 14)
1470
Index(['sequence', 'rank', 'overall_score', 'academic_reputation',
       'employer_reputation', 'faculty_student_ratio', 'citations_per_faculty',
       'international_faculty_ratio', 'international_students_ratio',
       'international_research_network', 'employment_outcomes',
       'sustainability', 'Fundos (US$)', 'country'],
      dtype='str')
<class 'pandas.DataFrame'>
Index: 105 entries, Massachusetts Institute of Technology (MIT) to Uppsala University
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   sequence                        105 non-null    int64
 1   rank                            105 non-null    int64
 2   overall_score                   105 non-null    float64
 3   academic_reputation             105 non-null    float64
 4   employer_reputation             105 non-null    float64
 5   faculty_student_ratio           105 non-null    float64
 6   citations_per_faculty           105 non-null    float64
 7   international_faculty_ratio     105 non-null    float64
 8   international_students_ratio    105 non-null    float64
 9   international_research_network  105 non-null    float64
 10  employment_outcomes             105 non-null    float64
 11  sustainability                  105 non-null    float64
 12  Fundos (US$)                    105 non-null    float64
 13  country                         30 non-null     str
dtypes: float64(11), int64(2), str(1)
memory usage: 12.3+ KB
None
sequence                            int64
rank                                int64
overall_score                     float64
academic_reputation               float64
employer_reputation               float64
faculty_student_ratio             float64
citations_per_faculty             float64
international_faculty_ratio       float64
international_students_ratio      float64
international_research_network    float64
employment_outcomes               float64
sustainability                    float64
Fundos (US$)                      float64
country                               str
dtype: object
                                                       country
university
Massachusetts Institute of Technology (MIT)      United States
University of Cambridge                         United Kingdom
University of Oxford                            United Kingdom
Harvard University                               United States
Stanford University                              United States
...                                                        ...
University of Nottingham                        United Kingdom
University of Wisconsin-Madison                  United States
Pontificia Universidad CatÃ³lica de Chile (UC)           Chile
The University of Sheffield                     United Kingdom
Uppsala University                                      Sweden

[105 rows x 1 columns]

C:\Users\ecalderonf\AppData\Local\Temp\ipykernel_17540\4285867041.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df_csv_universidades.select_dtypes(include = 'O'))

In [30]:
print(df_csv_universidades.isnull())

                                                sequence   rank  \
university
Massachusetts Institute of Technology (MIT)        False  False
University of Cambridge                            False  False
University of Oxford                               False  False
Harvard University                                 False  False
Stanford University                                False  False
...                                                  ...    ...
University of Nottingham                           False  False
University of Wisconsin-Madison                    False  False
Pontificia Universidad CatÃ³lica de Chile (UC)     False  False
The University of Sheffield                        False  False
Uppsala University                                 False  False

                                                overall_score  \
university
Massachusetts Institute of Technology (MIT)             False
University of Cambridge                                 False
University of Oxford                                    False
Harvard University                                      False
Stanford University                                     False
...                                                       ...
University of Nottingham                                False
University of Wisconsin-Madison                         False
Pontificia Universidad CatÃ³lica de Chile (UC)          False
The University of Sheffield                             False
Uppsala University                                      False

                                                academic_reputation  \
university
Massachusetts Institute of Technology (MIT)                   False
University of Cambridge                                       False
University of Oxford                                          False
Harvard University                                            False
Stanford University                                           False
...                                                             ...
University of Nottingham                                      False
University of Wisconsin-Madison                               False
Pontificia Universidad CatÃ³lica de Chile (UC)                False
The University of Sheffield                                   False
Uppsala University                                            False

                                                employer_reputation  \
university
Massachusetts Institute of Technology (MIT)                   False
University of Cambridge                                       False
University of Oxford                                          False
Harvard University                                            False
Stanford University                                           False
...                                                             ...
University of Nottingham                                      False
University of Wisconsin-Madison                               False
Pontificia Universidad CatÃ³lica de Chile (UC)                False
The University of Sheffield                                   False
Uppsala University                                            False

                                                faculty_student_ratio  \
university
Massachusetts Institute of Technology (MIT)                     False
University of Cambridge                                         False
University of Oxford                                            False
Harvard University                                              False
Stanford University                                             False
...                                                               ...
University of Nottingham                                        False
University of Wisconsin-Madison                                 False
Pontificia Universidad CatÃ³lica de Chile (UC)                  False
The University of Sheffield                                     False
Uppsala University                                              False

                                                citations_per_faculty  \
university
Massachusetts Institute of Technology (MIT)                     False
University of Cambridge                                         False
University of Oxford                                            False
Harvard University                                              False
Stanford University                                             False
...                                                               ...
University of Nottingham                                        False
University of Wisconsin-Madison                                 False
Pontificia Universidad CatÃ³lica de Chile (UC)                  False
The University of Sheffield                                     False
Uppsala University                                              False

                                                international_faculty_ratio  \
university
Massachusetts Institute of Technology (MIT)                           False
University of Cambridge                                               False
University of Oxford                                                  False
Harvard University                                                    False
Stanford University                                                   False
...                                                                     ...
University of Nottingham                                              False
University of Wisconsin-Madison                                       False
Pontificia Universidad CatÃ³lica de Chile (UC)                        False
The University of Sheffield                                           False
Uppsala University                                                    False

                                                international_students_ratio  \
university
Massachusetts Institute of Technology (MIT)                            False
University of Cambridge                                                False
University of Oxford                                                   False
Harvard University                                                     False
Stanford University                                                    False
...                                                                      ...
University of Nottingham                                               False
University of Wisconsin-Madison                                        False
Pontificia Universidad CatÃ³lica de Chile (UC)                         False
The University of Sheffield                                            False
Uppsala University                                                     False

                                                international_research_network  \
university
Massachusetts Institute of Technology (MIT)                              False
University of Cambridge                                                  False
University of Oxford                                                     False
Harvard University                                                       False
Stanford University                                                      False
...                                                                        ...
University of Nottingham                                                 False
University of Wisconsin-Madison                                          False
Pontificia Universidad CatÃ³lica de Chile (UC)                           False
The University of Sheffield                                              False
Uppsala University                                                       False

                                                employment_outcomes  \
university
Massachusetts Institute of Technology (MIT)                   False
University of Cambridge                                       False
University of Oxford                                          False
Harvard University                                            False
Stanford University                                           False
...                                                             ...
University of Nottingham                                      False
University of Wisconsin-Madison                               False
Pontificia Universidad CatÃ³lica de Chile (UC)                False
The University of Sheffield                                   False
Uppsala University                                            False

                                                sustainability  Fundos (US$)  \
university
Massachusetts Institute of Technology (MIT)              False         False
University of Cambridge                                  False         False
University of Oxford                                     False         False
Harvard University                                       False         False
Stanford University                                      False         False
...                                                        ...           ...
University of Nottingham                                 False         False
University of Wisconsin-Madison                          False         False
Pontificia Universidad CatÃ³lica de Chile (UC)           False         False
The University of Sheffield                              False         False
Uppsala University                                       False         False

                                                country
university
Massachusetts Institute of Technology (MIT)       False
University of Cambridge                           False
University of Oxford                              False
Harvard University                                False
Stanford University                               False
...                                                 ...
University of Nottingham                          False
University of Wisconsin-Madison                   False
Pontificia Universidad CatÃ³lica de Chile (UC)    False
The University of Sheffield                       False
Uppsala University                                False

[105 rows x 14 columns]

In [31]:
df_csv_universidades.isna()

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Cambridge,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Oxford,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Harvard University,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Stanford University,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
University of Nottingham,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Wisconsin-Madison,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Pontificia Universidad CatÃ³lica de Chile (UC),False,False,False,False,False,False,False,False,False,False,False,False,False,False
The University of Sheffield,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Uppsala University,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df_csv_universidades.isnull().sum()

sequence                           0
rank                               0
overall_score                      0
academic_reputation                0
employer_reputation                0
faculty_student_ratio              0
citations_per_faculty              0
international_faculty_ratio        0
international_students_ratio       0
international_research_network     0
employment_outcomes                0
sustainability                     0
Fundos (US$)                       0
country                           75
dtype: int64

In [33]:
df_csv_universidades.duplicated().sum()

np.int64(0)

In [34]:
df_csv_universidades.describe().T

,count,mean,std,min,25%,50%,75%,max
sequence,105.0,52.000000,30.454885,0.0,26.0,52.0,78.0,104.0
rank,105.0,52.800000,30.420578,1.0,26.0,53.0,79.0,105.0
overall_score,105.0,75.016190,11.454501,59.4,64.7,73.4,84.5,100.0
academic_reputation,105.0,82.724762,15.819406,43.4,71.3,85.0,97.6,100.0
employer_reputation,105.0,77.487619,21.561373,27.3,59.9,84.7,96.3,100.0
faculty_student_ratio,105.0,59.839048,31.077547,4.4,34.9,61.3,90.4,100.0
citations_per_faculty,105.0,70.589524,25.671385,1.7,51.4,72.4,93.5,100.0
international_faculty_ratio,105.0,70.159048,33.426261,6.0,39.1,88.9,99.1,100.0
international_students_ratio,105.0,67.961905,30.819878,2.3,45.7,78.8,96.8,100.0
international_research_network,105.0,74.531429,27.030529,1.3,58.3,85.2,95.5,100.0
employment_outcomes,105.0,63.664762,27.323877,13.4,39.6,66.0,92.5,100.0
sustainability,105.0,78.722857,21.728810,13.4,71.8,83.7,95.1,100.0
Fundos (US$),105.0,1.452381,2.589962,0.0,0.0,0.0,0.0,9.2

In [35]:
df_csv_universidades['rank'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  19,  21,  22,  23,  24,  25,  26,  28,  29,
        30,  32,  33,  34,  36,  37,  38,  40,  41,  42,  43,  44,  45,
        46,  47,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
        61,  62,  63,  64,  65,  67,  68,  69,  70,  71,  72,  73,  75,
        76,  78,  79,  80,  81,  83,  84,  85,  87,  89,  90,  91,  93,
        95,  97,  98,  99, 100, 102, 103, 104, 105])

In [36]:
df_csv_universidades['rank'].value_counts()

rank
47     3
17     2
19     2
26     2
28     2
      ..
99     1
102    1
103    1
104    1
105    1
Name: count, Length: 87, dtype: int64

In [37]:
# Usando el loc, accediendo por los nombres de las filas y las columnas
print(f'La proporción de alumnos en la universidad de Harvard usando el LOC es:  {df_csv_universidades.loc["Harvard University", "faculty_student_ratio"]}')

# Usando el iloc, accediendo por los índices, que empiezan en 0 como siempre en Python
print(f'La proporción de alumnos en la universidad de Harvard usando el ILOC es:  {df_csv_universidades.iloc[3,5]}')

La proporción de alumnos en la universidad de Harvard usando el LOC es:  98.3
La proporción de alumnos en la universidad de Harvard usando el ILOC es:  98.3

In [38]:
# Usando el loc
print(f'Los datos en la universidad de Harvard usando el LOC es: \n{df_csv_universidades.loc["Harvard University",:]}') #Aquí estamos indicando que nos busque los datos de una fila en específico y de TODAS LAS COLUMNAS, esto viene representado por los ':'

# usando el iloc
print(f'Los datos en la universidad de Harvard usando el ILOC es: \n{df_csv_universidades.iloc[3,:]}')

Los datos en la universidad de Harvard usando el LOC es:
sequence                                      3
rank                                          4
overall_score                              98.3
academic_reputation                       100.0
employer_reputation                       100.0
faculty_student_ratio                      98.3
citations_per_faculty                     100.0
international_faculty_ratio                84.6
international_students_ratio               66.8
international_research_network            100.0
employment_outcomes                       100.0
sustainability                             96.7
Fundos (US$)                                6.3
country                           United States
Name: Harvard University, dtype: object
Los datos en la universidad de Harvard usando el ILOC es:
sequence                                      3
rank                                          4
overall_score                              98.3
academic_reputation                       100.0
employer_reputation                       100.0
faculty_student_ratio                      98.3
citations_per_faculty                     100.0
international_faculty_ratio                84.6
international_students_ratio               66.8
international_research_network            100.0
employment_outcomes                       100.0
sustainability                             96.7
Fundos (US$)                                6.3
country                           United States
Name: Harvard University, dtype: object

In [39]:
# Usando el loc
print(f'Los datos de los países usando el LOC son:  {df_csv_universidades.loc[:,"country"]}')#En este caso, queremos que nos busque los datos de una columna en específico y de TODAS LAS FILAS, esto viene representado por los ':'

# usando el iloc
print(f'Los datos de los países usando el ILOC son:  {df_csv_universidades.iloc[:,-1]}')

Los datos de los países usando el LOC son:  university
Massachusetts Institute of Technology (MIT)        United States
University of Cambridge                           United Kingdom
University of Oxford                              United Kingdom
Harvard University                                 United States
Stanford University                                United States
                                                       ...
University of Nottingham                          United Kingdom
University of Wisconsin-Madison                    United States
Pontificia Universidad CatÃ³lica de Chile (UC)             Chile
The University of Sheffield                       United Kingdom
Uppsala University                                        Sweden
Name: country, Length: 105, dtype: str
Los datos de los países usando el ILOC son:  university
Massachusetts Institute of Technology (MIT)        United States
University of Cambridge                           United Kingdom
University of Oxford                              United Kingdom
Harvard University                                 United States
Stanford University                                United States
                                                       ...
University of Nottingham                          United Kingdom
University of Wisconsin-Madison                    United States
Pontificia Universidad CatÃ³lica de Chile (UC)             Chile
The University of Sheffield                       United Kingdom
Uppsala University                                        Sweden
Name: country, Length: 105, dtype: str

In [40]:
# Usando el loc
print(f'Los datos de los países usando el LOC son:  {df_csv_universidades.loc[["Stanford University","The University of Sheffield"],"country"]}')

# usando el iloc
print(f'Los datos de los países usando el ILOC son:  {df_csv_universidades.iloc[[4,-2],-1]}')

Los datos de los países usando el LOC son:  university
Stanford University             United States
The University of Sheffield    United Kingdom
Name: country, dtype: str
Los datos de los países usando el ILOC son:  university
Stanford University             United States
The University of Sheffield    United Kingdom
Name: country, dtype: str

In [41]:
# usando el iloc
print(f'Las puntuaciones de los datos de filas pares usando el ILOC son:  {df_csv_universidades.iloc[1::2,2]}')

Las puntuaciones de los datos de filas pares usando el ILOC son:  university
University of Cambridge                                        99.2
Harvard University                                             98.3
Imperial College London                                        97.8
National University of Singapore (NUS)                         92.7
University of California, Berkeley (UCB)                       90.4
University of Pennsylvania                                     89.4
The University of Melbourne                                    87.9
Yale University                                                87.7
Princeton University                                           87.0
The University of Sydney                                       86.7
The University of Edinburgh                                    86.1
UniversitÃ© PSL                                                85.8
Nanyang Technological University, Singapore (NTU Singapore)    84.5
Johns Hopkins University                                       84.5
University of California, Los Angeles (UCLA)                   83.8
The University of Manchester                                   82.2
Australian National University (ANU)                           81.5
EPFL â€“ Ã‰cole polytechnique fÃ©dÃ©rale de Lausanne           80.4
Institut Polytechnique de Paris                                79.5
King's College London                                          79.3
Monash University                                              78.2
Zhejiang University                                            77.8
Kyoto University                                               76.3
Northwestern University                                        76.2
Fudan University                                               74.4
Carnegie Mellon University                                     73.7
Ludwig-Maximilians-UniversitÃ¤t MÃ¼nchen                       72.5
KAIST - Korea Advanced Institute of Science & Technology       72.2
University of Texas at Austin                                  71.8
The Hong Kong University of Science and Technology             71.1
University of California, San Diego (UCSD)                     70.0
University of Illinois at Urbana-Champaign                     69.1
Universiti Malaya (UM)                                         68.7
The University of Auckland                                     68.0
City University of Hong Kong                                   67.7
The University of Western Australia                            66.9
KTH Royal Institute of Technology                              66.4
University of Glasgow                                          65.2
Durham University                                              65.1
Osaka University                                               63.9
University of Southampton                                      63.5
University of Birmingham                                       63.0
Universidade de SÃ£o Paulo                                     62.8
UniversitÃ¤t Heidelberg                                        62.2
University of Technology Sydney                                61.8
University of Zurich                                           61.6
Universidad Nacional AutÃ³noma de MÃ©xico (UNAM)               61.4
University of St Andrews                                       61.0
Freie Universitaet Berlin                                      60.8
Pohang University of Science And Technology (POSTECH)          60.4
University of Wisconsin-Madison                                60.0
The University of Sheffield                                    59.7
Name: overall_score, dtype: float64

# Filtrado de datos

In [42]:
pd.set_option('display.max_columns', None)

df_universidades = pd.read_csv('./data/DatosPandasUniversidades.csv', index_col = 2)

df_universidades.columns

Index(['sequence', 'rank', 'overall_score', 'academic_reputation',
       'employer_reputation', 'faculty_student_ratio', 'citations_per_faculty',
       'international_faculty_ratio', 'international_students_ratio',
       'international_research_network', 'employment_outcomes',
       'sustainability', 'Fundos (US$)', 'country'],
      dtype='str')

In [43]:
condición_USA = df_universidades["country"] == "United States"
universidades_USA = df_universidades[condición_USA]
universidades_USA

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
"University of California, Berkeley (UCB)",9,10,90.4,100.0,100.0,20.5,99.9,92.2,63.9,92.4,98.7,100.0,6.7,United States
University of Chicago,10,11,90.3,99.1,95.4,92.5,78.5,81.2,84.4,61.4,98.3,81.7,6.3,United States
University of Pennsylvania,11,12,89.4,96.4,89.1,99.9,68.4,96.0,70.3,83.3,100.0,99.9,6.2,United States
Cornell University,12,13,89.3,98.1,90.5,52.9,99.1,68.7,64.0,79.9,98.0,94.7,6.1,United States
California Institute of Technology (Caltech),14,15,87.8,96.1,93.7,100.0,100.0,100.0,81.0,22.8,34.2,41.4,5.7,United States
Yale University,15,16,87.7,99.9,99.9,100.0,45.8,89.8,78.8,85.8,99.9,99.2,5.6,United States
Princeton University,17,17,87.0,99.8,97.5,64.5,100.0,16.7,57.5,52.5,94.6,79.3,5.4,United States
Columbia University,22,23,85.9,99.6,98.3,100.0,40.7,56.1,96.8,97.6,99.9,94.2,4.9,United States
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States

In [44]:
condición_90 = (df_universidades["overall_score"] >= 90.0) & (df_universidades["overall_score"] < 95)
universidades_90 = df_universidades[condición_90]
universidades_90

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
ETH Zurich,6,7,93.3,98.8,83.6,72.1,98.9,100.0,98.5,96.0,79.1,88.4,5.9,Switzerland
National University of Singapore (NUS),7,8,92.7,99.4,88.6,76.5,93.2,100.0,81.9,76.3,100.0,88.1,5.7,Singapore
UCL,8,9,92.4,99.5,97.9,98.4,74.3,99.1,100.0,100.0,51.6,92.5,5.6,United Kingdom
"University of California, Berkeley (UCB)",9,10,90.4,100.0,100.0,20.5,99.9,92.2,63.9,92.4,98.7,100.0,6.7,United States
University of Chicago,10,11,90.3,99.1,95.4,92.5,78.5,81.2,84.4,61.4,98.3,81.7,6.3,United States

In [45]:
condicion_USA = df_universidades["country"] == "United States"
condicion_90 = (df_universidades["overall_score"] >= 50.0) & (df_universidades["overall_score"] < 90)
universidades_USA_90 = df_universidades[condicion_90 & condicion_USA]
universidades_USA_90

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
University of Pennsylvania,11,12,89.4,96.4,89.1,99.9,68.4,96.0,70.3,83.3,100.0,99.9,6.2,United States
Cornell University,12,13,89.3,98.1,90.5,52.9,99.1,68.7,64.0,79.9,98.0,94.7,6.1,United States
California Institute of Technology (Caltech),14,15,87.8,96.1,93.7,100.0,100.0,100.0,81.0,22.8,34.2,41.4,5.7,United States
Yale University,15,16,87.7,99.9,99.9,100.0,45.8,89.8,78.8,85.8,99.9,99.2,5.6,United States
Princeton University,17,17,87.0,99.8,97.5,64.5,100.0,16.7,57.5,52.5,94.6,79.3,5.4,United States
Columbia University,22,23,85.9,99.6,98.3,100.0,40.7,56.1,96.8,97.6,99.9,94.2,4.9,United States
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States

In [46]:
filtro_paises = ["China","Singapore"]
#Aplicamos la funcion isin()
china_singapore = df_universidades[df_universidades["country"].isin(filtro_paises)]
china_singapore

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
National University of Singapore (NUS),7,8,92.7,99.4,88.6,76.5,93.2,100.0,81.9,76.3,100.0,88.1,5.7,Singapore
Peking University,16,17,87.0,99.4,95.4,90.4,97.5,50.8,23.5,43.2,82.6,68.8,5.5,China
Tsinghua University,24,25,84.9,99.1,96.9,93.9,98.9,9.4,15.7,47.8,82.2,55.8,4.7,China

In [47]:
uni_99_100 = df_universidades[df_universidades["employer_reputation"].between(50, 80, inclusive = "right")]
uni_99_100

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
"Nanyang Technological University, Singapore (NTU Singapore)",25,26,84.5,91.0,67.1,77.6,94.4,100.0,80.2,66.1,68.4,78.2,4.6,NaN
The University of Hong Kong,26,26,84.5,97.6,51.4,82.9,82.3,100.0,99.0,42.7,99.5,97.3,0.0,NaN
Johns Hopkins University,27,28,84.5,87.3,59.7,100.0,89.4,64.4,91.4,98.1,74.5,84.6,0.0,NaN
Australian National University (ANU),33,34,81.5,93.2,70.2,34.9,92.8,100.0,93.3,78.5,43.9,87.4,0.0,NaN
EPFL â€“ Ã‰cole polytechnique fÃ©dÃ©rale de Lausanne,35,36,80.4,84.6,59.9,92.4,98.0,100.0,100.0,65.6,19.4,42.3,0.0,NaN
Monash University,41,42,78.2,88.4,75.2,9.6,88.4,100.0,100.0,86.8,61.0,71.8,0.0,NaN
The University of Queensland,42,43,78.1,87.1,73.7,21.6,87.0,100.0,100.0,95.0,44.4,73.1,0.0,NaN
Delft University of Technology,46,47,76.2,73.0,79.0,36.9,84.9,100.0,89.3,91.4,42.1,98.4,0.0,NaN
Northwestern University,47,47,76.2,83.8,60.2,98.9,70.3,48.2,44.2,79.2,97.7,78.0,0.0,NaN
Carnegie Mellon University,51,52,73.7,71.2,75.3,49.1,99.9,46.6,98.2,57.4,60.0,47.2,0.0,NaN
Duke University,56,57,72.0,85.7,69.3,100.0,40.2,16.8,52.2,90.0,89.3,95.0,0.0,NaN
Sorbonne University,58,59,71.7,88.6,53.2,43.3,85.4,35.2,49.8,100.0,39.5,75.8,0.0,NaN
"University of California, San Diego (UCSD)",61,62,70.0,89.1,50.4,49.6,74.3,68.1,51.3,94.9,17.7,72.5,0.0,NaN
University of Washington,62,63,69.2,84.0,50.4,19.1,93.5,19.0,33.2,94.0,70.0,88.1,0.0,NaN
University of Illinois at Urbana-Champaign,63,64,69.1,85.0,70.8,7.5,86.5,11.1,49.2,76.4,66.0,83.5,0.0,NaN
KTH Royal Institute of Technology,73,73,66.4,45.7,51.1,66.2,90.2,93.2,68.1,80.7,56.9,96.1,0.0,NaN
University of Leeds,74,75,65.5,70.3,76.7,37.3,42.3,85.2,90.0,98.7,37.8,90.9,0.0,NaN
University of Glasgow,75,76,65.2,76.3,70.7,41.7,31.8,96.0,99.5,90.0,26.7,99.5,0.0,NaN
University of Southampton,81,81,63.5,51.5,51.2,52.8,71.4,96.1,97.4,97.0,32.5,82.7,0.0,NaN
Pennsylvania State University,82,83,63.1,77.5,63.0,28.4,62.9,23.4,26.8,96.6,47.5,95.1,0.0,NaN
University of Birmingham,83,84,63.0,67.5,75.7,41.3,38.2,92.3,83.9,96.0,29.5,80.4,0.0,NaN
Lomonosov Moscow State University,86,87,62.2,81.2,78.3,99.8,4.6,20.3,92.3,85.2,82.2,13.4,0.0,NaN
UniversitÃ¤t Heidelberg,87,87,62.2,78.3,52.0,99.7,38.2,52.5,50.4,89.7,19.8,42.6,0.0,NaN
University of Technology Sydney,89,90,61.8,43.4,57.8,9.0,95.3,96.6,93.6,79.7,30.1,93.1,0.0,NaN
Boston University,92,93,61.4,61.7,68.3,32.7,60.1,21.6,87.5,72.6,68.6,85.9,0.0,NaN
University of St Andrews,95,95,61.0,47.3,67.2,64.9,57.7,98.7,100.0,51.1,22.4,92.1,0.0,NaN
Freie Universitaet Berlin,97,98,60.8,80.8,51.0,4.4,71.4,62.8,43.6,84.9,21.9,60.1,0.0,NaN
Pohang University of Science And Technology (POSTECH),99,100,60.4,51.6,75.9,99.9,98.3,33.8,2.6,1.3,13.4,16.9,0.0,NaN
University of Nottingham,100,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
The University of Sheffield,103,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom

In [48]:
df_universidades.isnull().sum()

sequence                           0
rank                               0
overall_score                      0
academic_reputation                0
employer_reputation                0
faculty_student_ratio              0
citations_per_faculty              0
international_faculty_ratio        0
international_students_ratio       0
international_research_network     0
employment_outcomes                0
sustainability                     0
Fundos (US$)                       0
country                           75
dtype: int64

In [49]:
universidades_united = df_universidades[df_universidades["country"].str.contains("United",case = False, na = False)]
universidades_united

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
Imperial College London,5,6,97.8,98.3,99.4,98.5,94.0,100.0,100.0,96.7,83.0,94.4,6.1,United Kingdom
UCL,8,9,92.4,99.5,97.9,98.4,74.3,99.1,100.0,100.0,51.6,92.5,5.6,United Kingdom
"University of California, Berkeley (UCB)",9,10,90.4,100.0,100.0,20.5,99.9,92.2,63.9,92.4,98.7,100.0,6.7,United States
University of Chicago,10,11,90.3,99.1,95.4,92.5,78.5,81.2,84.4,61.4,98.3,81.7,6.3,United States
University of Pennsylvania,11,12,89.4,96.4,89.1,99.9,68.4,96.0,70.3,83.3,100.0,99.9,6.2,United States
Cornell University,12,13,89.3,98.1,90.5,52.9,99.1,68.7,64.0,79.9,98.0,94.7,6.1,United States
California Institute of Technology (Caltech),14,15,87.8,96.1,93.7,100.0,100.0,100.0,81.0,22.8,34.2,41.4,5.7,United States
Yale University,15,16,87.7,99.9,99.9,100.0,45.8,89.8,78.8,85.8,99.9,99.2,5.6,United States
Princeton University,17,17,87.0,99.8,97.5,64.5,100.0,16.7,57.5,52.5,94.6,79.3,5.4,United States
The University of Edinburgh,21,22,86.1,98.1,96.9,72.4,58.7,98.8,99.9,99.6,48.1,99.7,5.0,United Kingdom
Columbia University,22,23,85.9,99.6,98.3,100.0,40.7,56.1,96.8,97.6,99.9,94.2,4.9,United States
University of Nottingham,100,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States
The University of Sheffield,103,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom

In [50]:
df_universidades.filter(items = ['academic_reputation','international_students_ratio'])

,academic_reputation,international_students_ratio
university,,
Massachusetts Institute of Technology (MIT),100.0,88.2
University of Cambridge,100.0,95.8
University of Oxford,100.0,98.2
Harvard University,100.0,66.8
Stanford University,100.0,51.2
...,...,...
University of Nottingham,60.7,75.2
University of Wisconsin-Madison,80.2,22.8
Pontificia Universidad CatÃ³lica de Chile (UC),92.9,3.5
The University of Sheffield,58.7,97.5
Uppsala University,62.7,82.4

In [51]:
df_universidades.filter(like = 'University',axis = 0)

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,3,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,4,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
National University of Singapore (NUS),7,8,92.7,99.4,88.6,76.5,93.2,100.0,81.9,76.3,100.0,88.1,5.7,Singapore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pohang University of Science And Technology (POSTECH),99,100,60.4,51.6,75.9,99.9,98.3,33.8,2.6,1.3,13.4,16.9,0.0,NaN
University of Nottingham,100,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
University of Wisconsin-Madison,101,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States
The University of Sheffield,103,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom
Uppsala University,104,105,59.4,62.7,30.5,47.7,45.6,98.3,82.4,95.5,58.2,99.4,0.0,Sweden

# Operaciones aritméticas

In [52]:
#Primero creamos el diccionario con los datos.
datos_personas = {
    'Ana':{ 'Altura (cm)': 160, 'Peso (kg)': 55},
    'Carlos':{ 'Altura (cm)': 175, 'Peso (kg)': 70},
    'María':{ 'Altura (cm)': 162, 'Peso (kg)': 60}}
#Ahora crearemos el DataFrame
personas=pd.DataFrame(datos_personas)

personas

             Ana  Carlos  María
Altura (cm)  160     175    162
Peso (kg)     55      70     60

In [53]:
# suma
personas_add = personas.add(1)

personas_add

             Ana  Carlos  María
Altura (cm)  161     176    163
Peso (kg)     56      71     61

In [54]:
# resta
personas_sub = personas.sub(10)

personas_sub

             Ana  Carlos  María
Altura (cm)  150     165    152
Peso (kg)     45      60     50

In [55]:
# Multiplicar
personas_prod = personas.mul(2)
personas_prod

             Ana  Carlos  María
Altura (cm)  320     350    324
Peso (kg)    110     140    120

In [56]:
# Division
personas_div = personas.div(3)
personas_div

                   Ana     Carlos  María
Altura (cm)  53.333333  58.333333   54.0
Peso (kg)    18.333333  23.333333   20.0

In [57]:
# floor
personas_floor = personas.floordiv(3)

personas_floor

             Ana  Carlos  María
Altura (cm)   53      58     54
Peso (kg)     18      23     20

In [58]:
#mod
personas_mod = personas.mod(3)

personas_mod

             Ana  Carlos  María
Altura (cm)    1       1      0
Peso (kg)      1       1      0

In [59]:
#pow
personas_pow = personas.pow(2)

personas_pow

               Ana  Carlos  María
Altura (cm)  25600   30625  26244
Peso (kg)     3025    4900   3600

# Eliminar columnas o filas

In [60]:
df_universidades.head(3)

,sequence,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),0,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,1,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,2,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom

In [61]:
# Elilmina la columna Sequence
df_universidades.drop('sequence',axis = 1,inplace = True)

df_universidades.head(3)

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom

In [62]:
universidades_sin_mit = df_universidades.drop('Massachusetts Institute of Technology (MIT)', axis=0, inplace=False)

universidades_sin_mit

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country
university,,,,,,,,,,,,,
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom
Harvard University,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States
Stanford University,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States
Imperial College London,6,97.8,98.3,99.4,98.5,94.0,100.0,100.0,96.7,83.0,94.4,6.1,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...
University of Nottingham,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom
University of Wisconsin-Madison,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States
Pontificia Universidad CatÃ³lica de Chile (UC),103,59.9,92.9,99.5,20.6,11.6,16.4,3.5,56.8,76.3,91.3,0.0,Chile
The University of Sheffield,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom
Uppsala University,105,59.4,62.7,30.5,47.7,45.6,98.3,82.4,95.5,58.2,99.4,0.0,Sweden

# Generar columnas

In [63]:
#Vamos a crear una columna con la media de la reputación académica y de empleado
calculo_media = (df_universidades['academic_reputation'] + df_universidades['employer_reputation'])/2
df_universidades['mean_reputation_direct_assignment'] = calculo_media

df_universidades.head(3)

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country,mean_reputation_direct_assignment
university,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States,100.0
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom,100.0
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom,100.0

In [64]:
universidades_2 = df_universidades.assign(mean_reputation_assign_method = calculo_media) #Recordemos que la variable calculo_media la hemos creado en el apartado de asignación directa

universidades_2.head(3)

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country,mean_reputation_direct_assignment,mean_reputation_assign_method
university,,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States,100.0,100.0
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom,100.0,100.0
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom,100.0,100.0

In [65]:
#Vamos a crear una variable con el valor de la cantidad de columnas que tiene nuestro DataFrame
num_col=len(universidades_2.columns)
#Esta variable la usaremos para insertar las nueva columna al final del DataFrame
universidades_2.insert(num_col,'mean_reputation_insert_method_2',calculo_media)

universidades_2

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country,mean_reputation_direct_assignment,mean_reputation_assign_method,mean_reputation_insert_method_2
university,,,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States,100.0,100.0,100.0
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom,100.0,100.0,100.0
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom,100.0,100.0,100.0
Harvard University,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States,100.0,100.0,100.0
Stanford University,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States,100.0,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
University of Nottingham,100,60.4,60.7,72.1,32.2,46.5,90.0,75.2,98.4,24.4,80.0,0.0,United Kingdom,66.4,66.4,66.4
University of Wisconsin-Madison,102,60.0,80.2,47.8,61.3,37.4,30.9,22.8,83.6,73.1,83.7,0.0,United States,64.0,64.0,64.0
Pontificia Universidad CatÃ³lica de Chile (UC),103,59.9,92.9,99.5,20.6,11.6,16.4,3.5,56.8,76.3,91.3,0.0,Chile,96.2,96.2,96.2
The University of Sheffield,104,59.7,58.7,52.3,54.7,46.9,84.0,97.5,96.1,24.9,76.3,0.0,United Kingdom,55.5,55.5,55.5
Uppsala University,105,59.4,62.7,30.5,47.7,45.6,98.3,82.4,95.5,58.2,99.4,0.0,Sweden,46.6,46.6,46.6

In [66]:
#Vamos a calcular la media entre la reputación académica y la reputación del empledado para cada universidad. 
universidades_2.eval('mean_acaddemic_employer=(academic_reputation + employer_reputation)/2',inplace = True)

In [67]:
#Vamos a calcular la media total de esta nueva columna creada
universidades_2.eval('mean_acaddemic_employer.mean()')

universidades_2.head(5)

,rank,overall_score,academic_reputation,employer_reputation,faculty_student_ratio,citations_per_faculty,international_faculty_ratio,international_students_ratio,international_research_network,employment_outcomes,sustainability,Fundos (US$),country,mean_reputation_direct_assignment,mean_reputation_assign_method,mean_reputation_insert_method_2,mean_acaddemic_employer
university,,,,,,,,,,,,,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100.0,95.2,9.2,United States,100.0,100.0,100.0,100.0
University of Cambridge,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100.0,97.3,7.8,United Kingdom,100.0,100.0,100.0,100.0
University of Oxford,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100.0,97.8,6.7,United Kingdom,100.0,100.0,100.0,100.0
Harvard University,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100.0,96.7,6.3,United States,100.0,100.0,100.0,100.0
Stanford University,5,98.1,100.0,100.0,100.0,99.9,99.9,51.2,95.8,100.0,94.4,6.2,United States,100.0,100.0,100.0,100.0

# Group by

● count() : Número de observaciones no nulas

● describe() : Resumen de los principales estadísticos

● sum() : Suma de todos los valores

● mean() : Media de los valores

● median() : Mediana de los valores

● min() : Valor mínimo

● max() : Valor máximo

● std() : Desviación estándar

● var() : Varianza

● size() : Tamaño de los grupos.

● first(): Devuelve la primera entrada de cada grupo.

● last(): Devuelve la última entrada de cada grupo.

In [68]:
# Importamos las librerías que necesitamos
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

user = pd.read_csv('./data/DatosUsuariosRedesSociales.csv')

user.sample(5)

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car
314,47,non-binary,7,Facebook,Travel,United States,Urban,Student,19608,False,False,False
100,25,female,7,Instagram,Lifestlye,Australia,Rural,Student,17532,True,True,True
724,64,non-binary,1,YouTube,Travel,United States,Sub_Urban,Software Engineer,10561,False,True,False
801,47,non-binary,2,Facebook,Sports,United Kingdom,Sub_Urban,Marketer Manager,12513,True,False,True
927,59,non-binary,6,YouTube,Lifestlye,United States,Rural,Student,18539,False,False,True

In [69]:
user.groupby('platform').mean(numeric_only = True)

,age,time_spent,income,indebt,isHomeOwner,Owns_Car
platform,,,,,,
Facebook,40.846906,5.055375,15250.276873,0.485342,0.504886,0.524430
Instagram,40.892562,5.151515,14662.454545,0.506887,0.465565,0.523416
YouTube,41.218182,4.869697,15183.384848,0.496970,0.557576,0.569697

In [70]:
edad_media = user.groupby('platform')['age'].mean()
edad_media

platform
Facebook     40.846906
Instagram    40.892562
YouTube      41.218182
Name: age, dtype: float64

In [71]:
edad_media = edad_media.reset_index()
edad_media

    platform        age
0   Facebook  40.846906
1  Instagram  40.892562
2    YouTube  41.218182

In [72]:
ingresos_residencia = user.groupby('demographics')['income'].median().reset_index()
ingresos_residencia

  demographics   income
0        Rural  14774.0
1    Sub_Urban  14631.0
2        Urban  15193.0

In [73]:
tiempo_uso = user.groupby('location')['time_spent'].sum().reset_index()
tiempo_uso

         location  time_spent
0       Australia        1837
1  United Kingdom        1615
2   United States        1577

In [74]:
salario_profesion = user.groupby('profession')['income'].agg(['mean','median','std','max','min']).reset_index()
salario_profesion

          profession          mean   median          std    max    min
0   Marketer Manager  14927.335211  14859.0  3015.541853  19980  10028
1  Software Engineer  14876.511905  14657.0  2976.018890  19969  10012
2            Student  15265.731392  15316.0  2866.081570  19957  10075

In [75]:
user.groupby('platform').get_group('Facebook').tail()

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car
979,37,female,6,Facebook,Sports,Australia,Urban,Marketer Manager,19034,True,False,False
981,64,male,6,Facebook,Sports,United Kingdom,Urban,Marketer Manager,13641,True,False,True
987,28,female,9,Facebook,Travel,Australia,Sub_Urban,Software Engineer,14662,False,True,True
988,53,male,4,Facebook,Lifestlye,United Kingdom,Sub_Urban,Student,14326,True,False,False
991,20,non-binary,7,Facebook,Travel,Australia,Sub_Urban,Software Engineer,18281,False,False,True

# Método Apply

In [76]:
# Importamos las librerías que necesitamos
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

user = pd.read_csv('./data/DatosUsuariosRedesSociales.csv')

user.sample(5)

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car
199,29,female,8,Facebook,Sports,Australia,Sub_Urban,Software Engineer,12040,False,True,False
854,31,non-binary,4,Instagram,Sports,Australia,Rural,Marketer Manager,12220,False,False,True
150,47,male,1,Facebook,Sports,United Kingdom,Rural,Student,17938,True,False,False
492,45,non-binary,7,Facebook,Sports,United Kingdom,Rural,Marketer Manager,14601,True,False,False
151,54,female,1,YouTube,Lifestlye,United States,Urban,Student,14141,False,False,True

In [77]:
def categorizar_edad (numero):

    if 18 <= numero <= 28:
        return 'Jóven adulto'
    elif 29 <= numero <= 39:
        return 'Adulto jóven'
    elif 40 <= numero <= 50:
        return 'Mediana edad'
    else:
        return 'Adultos mayores'

In [78]:
user['age_category'] = user['age'].apply(categorizar_edad)
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category
0,56,male,3,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774,True,False,False,Adultos mayores
1,46,female,2,Facebook,Travel,United Kingdom,Urban,Student,10564,True,True,True,Mediana edad
2,32,male,8,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258,False,False,False,Adulto jóven
3,60,non-binary,5,Instagram,Travel,United Kingdom,Urban,Student,12500,False,True,False,Adultos mayores
4,25,male,1,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566,False,True,True,Jóven adulto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536,False,True,False,Jóven adulto
996,40,non-binary,6,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711,True,False,False,Mediana edad
997,27,non-binary,5,YouTube,Travel,United Kingdom,Rural,Student,17595,True,False,True,Jóven adulto
998,61,female,4,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273,True,True,False,Adultos mayores
999,19,female,8,YouTube,Travel,Australia,Rural,Student,16284,False,True,False,Jóven adulto

In [79]:
user['income'].dtype

dtype('int64')

In [80]:
#Definimos la función
def cambiar_float(numero):
    """
    Función para cambiar el tipo de un número a float.

    Parámetros:
    - numero (int): Número que se va a convertir.

    Retorna:
    - float: El número proporcionado con el tipo cambiado a float.
    """
    return float(numero)

#Llamamos a la función
user['income'] = user['income'].apply(cambiar_float)

#Comprobamos
user['income'].dtype

dtype('float64')

In [81]:
#Vamos a hacer lo mismo para la columna 'time_spent'
user['time_spent'] = user['time_spent'].apply(lambda x: float(x))

user['time_spent'].dtype

dtype('float64')

In [82]:
user['Owns_Car'] = user['Owns_Car'].apply(lambda x: 'yes' if x == True else 'no')
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category
0,56,male,3.0,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774.0,True,False,no,Adultos mayores
1,46,female,2.0,Facebook,Travel,United Kingdom,Urban,Student,10564.0,True,True,yes,Mediana edad
2,32,male,8.0,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258.0,False,False,no,Adulto jóven
3,60,non-binary,5.0,Instagram,Travel,United Kingdom,Urban,Student,12500.0,False,True,no,Adultos mayores
4,25,male,1.0,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566.0,False,True,yes,Jóven adulto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8.0,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536.0,False,True,no,Jóven adulto
996,40,non-binary,6.0,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711.0,True,False,no,Mediana edad
997,27,non-binary,5.0,YouTube,Travel,United Kingdom,Rural,Student,17595.0,True,False,yes,Jóven adulto
998,61,female,4.0,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273.0,True,True,no,Adultos mayores
999,19,female,8.0,YouTube,Travel,Australia,Rural,Student,16284.0,False,True,no,Jóven adulto

In [83]:
def travel_female(col_interests,col_gender):
    """
    Función para identificar un usuario con unas características concretas.

    Parámetros:
    - col_interests (str): Columna con los intereses del usuario.

    - col_gender (str): Columna con el género del usuario

    Retorna:
    - bool: Si las condiciones se cumplen o no
    """
    if col_interests == 'Travel' and col_gender == 'female':
        return True
    else:
        return False

In [84]:
user['target_audiences']=user.apply(lambda x: travel_female(x['interests'],x['gender']),axis=1)
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category,target_audiences
0,56,male,3.0,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774.0,True,False,no,Adultos mayores,False
1,46,female,2.0,Facebook,Travel,United Kingdom,Urban,Student,10564.0,True,True,yes,Mediana edad,True
2,32,male,8.0,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258.0,False,False,no,Adulto jóven,False
3,60,non-binary,5.0,Instagram,Travel,United Kingdom,Urban,Student,12500.0,False,True,no,Adultos mayores,False
4,25,male,1.0,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566.0,False,True,yes,Jóven adulto,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8.0,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536.0,False,True,no,Jóven adulto,False
996,40,non-binary,6.0,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711.0,True,False,no,Mediana edad,False
997,27,non-binary,5.0,YouTube,Travel,United Kingdom,Rural,Student,17595.0,True,False,yes,Jóven adulto,False
998,61,female,4.0,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273.0,True,True,no,Adultos mayores,False
999,19,female,8.0,YouTube,Travel,Australia,Rural,Student,16284.0,False,True,no,Jóven adulto,True

In [85]:
def error_edad (edad, num):
    """
    Función corregir la edad introducida en nuestros datos.

    Parámetros:
    - edad (int): Columna con la edad errónea del usuario.

    - num (int): Cantidad de años a sumar

    Retorna:
    - int: Edad corregida
    """
    return (edad + num)

In [86]:
user['age']=user['age'].apply(error_edad,num=10)
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category,target_audiences
0,66,male,3.0,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774.0,True,False,no,Adultos mayores,False
1,56,female,2.0,Facebook,Travel,United Kingdom,Urban,Student,10564.0,True,True,yes,Mediana edad,True
2,42,male,8.0,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258.0,False,False,no,Adulto jóven,False
3,70,non-binary,5.0,Instagram,Travel,United Kingdom,Urban,Student,12500.0,False,True,no,Adultos mayores,False
4,35,male,1.0,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566.0,False,True,yes,Jóven adulto,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,32,female,8.0,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536.0,False,True,no,Jóven adulto,False
996,50,non-binary,6.0,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711.0,True,False,no,Mediana edad,False
997,37,non-binary,5.0,YouTube,Travel,United Kingdom,Rural,Student,17595.0,True,False,yes,Jóven adulto,False
998,71,female,4.0,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273.0,True,True,no,Adultos mayores,False
999,29,female,8.0,YouTube,Travel,Australia,Rural,Student,16284.0,False,True,no,Jóven adulto,True

In [87]:
def saludo():
    """
    Función que devuelve un saludo cuando la llamamos.

    Parámetros:

    Retorna:
    - str: La frase de saludo
    """
    return 'Hola, buenos días'

In [88]:
user.apply(lambda x: saludo())

age                 Hola, buenos días
gender              Hola, buenos días
time_spent          Hola, buenos días
platform            Hola, buenos días
interests           Hola, buenos días
location            Hola, buenos días
demographics        Hola, buenos días
profession          Hola, buenos días
income              Hola, buenos días
indebt              Hola, buenos días
isHomeOwner         Hola, buenos días
Owns_Car            Hola, buenos días
age_category        Hola, buenos días
target_audiences    Hola, buenos días
dtype: str

In [89]:
# Combinación de DataFrames

In [90]:
# Tratamiento de datos
import pandas as pd
import numpy as np

#Cargamos los tres csv.
coches_2024 = pd.read_csv('./data/datos_ford_2024.csv', index_col = 0)
print(coches_2024.head())

coches_2023 = pd.read_csv('./data/datos_ford_2023.csv', index_col = 0)
print(coches_2023.head())

coches_caracteristicas = pd.read_csv('./data/datos_ford_caracteristicas.csv', index_col = 0)
print(coches_caracteristicas.head())

                 VIN   modelo_coche  id_del_vendedor fecha_venta
0  1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
1  2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
2  3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
3  4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
4  5FAHP3K22CL100005    Ford Escape              102  2024-01-05
                 VIN   modelo_coche  id_del_vendedor fecha_venta
0  1FABPBLT3JL200051    Ford Fiesta              113  2023-01-15
1  2FADP4EJ9CL200052     Ford Focus              114  2023-02-02
2  3FABP4EJ8CR200053   Ford Mustang              115  2023-01-20
3  4FADS2LJ2CL200054  Ford Explorer              113  2023-02-10
4  5FAHP3K22CL200055    Ford Escape              114  2023-01-05
                 VIN  numero_puertas  camara_trasera  sensor_aparcamiento
0  1FABPBLT3JL100001               5            True                 True
1  2FADP4EJ9CL100002               3           False                False
2  3FABP4EJ8CR100003               5            True                 True
3  4FADS2LJ2CL100004               5           False                 True
4  5FAHP3K22CL100005               3           False                False

In [91]:
concat_1 = pd.concat([coches_2024,coches_2023],axis = 1,join = 'inner')
concat_1.head()

,VIN,modelo_coche,id_del_vendedor,fecha_venta,VIN,modelo_coche,id_del_vendedor,fecha_venta
0,1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,1FABPBLT3JL200051,Ford Fiesta,113,2023-01-15
1,2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,2FADP4EJ9CL200052,Ford Focus,114,2023-02-02
2,3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,3FABP4EJ8CR200053,Ford Mustang,115,2023-01-20
3,4FADS2LJ2CL100004,Ford Explorer,101,2024-02-10,4FADS2LJ2CL200054,Ford Explorer,113,2023-02-10
4,5FAHP3K22CL100005,Ford Escape,102,2024-01-05,5FAHP3K22CL200055,Ford Escape,114,2023-01-05

In [92]:
concat_0 = pd.concat([coches_2024,coches_2023],axis = 0,join='inner')
concat_0

                  VIN   modelo_coche  id_del_vendedor fecha_venta
0   1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
1   2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
2   3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
3   4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
4   5FAHP3K22CL100005    Ford Escape              102  2024-01-05
..                ...            ...              ...         ...
45  1FABP4BJ3DL200096    Ford Fusion              127  2023-11-18
46  2FABP4AV1FL200097    Ford Bronco              125  2023-11-25
47  3FAHP0JA4CL200098      Ford Edge              126  2023-12-02
48  4FABP4EJ7CL200099    Ford Ranger              127  2023-12-10
49  5FABP4CN0CL200100   Ford Transit              125  2023-12-18

[100 rows x 4 columns]

df_left.merge(df_right, how = 'inner', on = None, left_on = None, right_on = None)
'''
Donde:

- df_left y df_right: Son los DataFrames que se van a combinar.
- how (opcional): Especifica el tipo de unión que se va a realizar.
    - `inner` : Intersección de las claves de ambos DataFrames, es decir, sólo los valores comunes.
    - `left` : Valores comunes de ambos DataFrames y no comunes del izquierdo.
    - `right` : Valores comunes de ambos DataFrames y no comunes del derecho.
    - `outer` : Utiliza TODOS los valores de ambos DataFrames.
- on: Especifica las columnas comunes en las que se van a basar la unión. Estas columnas DEBEN TENER EL MISMO NOMBRE.
- left_on: Nombre de la columna del df_left en la que se basará la unión.
- right_on: Nombre de la columna del df_right en la que se basará la unión.
'''

In [93]:
#Comprobemos primero los datos del 2023.
coches_2023_merge = coches_2023.merge(coches_caracteristicas, how = 'inner', on = 'VIN')
coches_2023_merge

Empty DataFrame
Columns: [VIN, modelo_coche, id_del_vendedor, fecha_venta, numero_puertas, camara_trasera, sensor_aparcamiento]
Index: []

In [94]:
#Comprobemos ahora los datos del 2024.
coches_2024_merge = coches_2024.merge(coches_caracteristicas, how = 'inner', on = 'VIN').head(3)
coches_2024_merge

,VIN,modelo_coche,id_del_vendedor,fecha_venta,numero_puertas,camara_trasera,sensor_aparcamiento
0,1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,5,True,True
1,2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,3,False,False
2,3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,5,True,True

df_join = df_left.join(df_right, how = 'tipo_de_join', lsuffix = '', rsuffix = '')
'''
Donde:

- df_join: DataFrame resultado.
- df_left y df_right: Son los DataFrames que se van a combinar.
- how (opcional): Especifica el tipo de unión que se va a realizar.
    - inner : Intersección de las claves de ambos DataFrames, es decir, sólo los valores comunes.
    - left : Valores comunes de ambos DataFrames y no comunes del izquierdo.
    - right : Valores comunes de ambos DataFrames y no comunes del derecho.
    - outer : Utiliza TODOS los valores de ambos DataFrames.
- lsuffix (opcional): Por defecto nada. Si coinciden columnas en los DataFrames que queremos unir, será el sufijo que aparecerá en esas columnas en el DataFrame izquierdo.
- rsuffix (opcional): Por defecto nada. Si coinciden columnas en los DataFrames que queremos unir, será el sufijo que aparecerá en esas columnas en el DataFrame derecho.
'''

In [95]:
coches_2024.set_index(["VIN"], inplace = True)
coches_2024.head()

                    modelo_coche  id_del_vendedor fecha_venta
VIN
1FABPBLT3JL100001    Ford Fiesta              101  2024-01-15
2FADP4EJ9CL100002     Ford Focus              102  2024-02-02
3FABP4EJ8CR100003   Ford Mustang              103  2024-01-20
4FADS2LJ2CL100004  Ford Explorer              101  2024-02-10
5FAHP3K22CL100005    Ford Escape              102  2024-01-05

In [96]:
coches_caracteristicas.set_index(["VIN"], inplace = True)
coches_caracteristicas.head()

                   numero_puertas  camara_trasera  sensor_aparcamiento
VIN
1FABPBLT3JL100001               5            True                 True
2FADP4EJ9CL100002               3           False                False
3FABP4EJ8CR100003               5            True                 True
4FADS2LJ2CL100004               5           False                 True
5FAHP3K22CL100005               3           False                False

In [97]:
coches_join = coches_2024.join(coches_caracteristicas, on = 'VIN')
coches_join.head()

,modelo_coche,id_del_vendedor,fecha_venta,numero_puertas,camara_trasera,sensor_aparcamiento
VIN,,,,,,
1FABPBLT3JL100001,Ford Fiesta,101,2024-01-15,5,True,True
2FADP4EJ9CL100002,Ford Focus,102,2024-02-02,3,False,False
3FABP4EJ8CR100003,Ford Mustang,103,2024-01-20,5,True,True
4FADS2LJ2CL100004,Ford Explorer,101,2024-02-10,5,False,True
5FAHP3K22CL100005,Ford Escape,102,2024-01-05,3,False,False

# Pivotado de datos

df.pivot_table(values = None, index = None, columns = None, aggfunc = 'mean')
'''
Donde:

- df: DataFrame que vamos a usar.
- values: Columna o columnas a realizar la función e agregación.
- index: Claves de donde se van a hacer las agrupaciones. Serán los valores del índice del DataFrame.
- columna: Valores que van a tener los nombres de las columnas.
- aggfunc: Función de agregación que se va a realizar sobre los datos.
'''

In [98]:
concat_0.pivot_table(values = 'fecha_venta', index = 'id_del_vendedor', columns = 'modelo_coche', aggfunc = 'count')

modelo_coche,Ford Bronco,Ford Edge,Ford Escape,Ford Explorer,Ford Fiesta,Ford Focus,Ford Fusion,Ford Mustang,Ford Ranger,Ford Transit
id_del_vendedor,,,,,,,,,,
101,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
102,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
103,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
104,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
105,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
106,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
107,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
108,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
110,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
111,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
113,2.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,2.0
114,NaN,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN
116,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
117,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
118,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
119,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
120,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
122,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
123,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
124,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN
125,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,1.0
126,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN

# método melt

pd.melt(df, id_vars = None, value_vars = None, var_name = None, value_name = None)
'''
Donde:

- df: DataFrame que vamos a usar.
- id_vars: Columnas que serán las variables identificadoras. Estas no van a cambiar al generar el nuevo DataFrame.
- value_vars: Columnas que se van a fundir o fusionarse.
- var_name: Nombre de las nuevas columnas variable a generar.
- value_name Nombre de las nuevas columnas valores a generar.
'''

In [99]:
#Antes vamos a transformar el DataFrame creado durante el mergeo para poder ver mejor el resultado del método melt
coches_2024_merge=coches_2024_merge.head(3)

pd.melt(coches_2024_merge, id_vars = 'modelo_coche', value_vars = ['numero_puertas', 'camara_trasera', 'sensor_aparcamiento'], var_name = 'Características', value_name = 'Valor')

   modelo_coche      Características  Valor
0   Ford Fiesta       numero_puertas      5
1    Ford Focus       numero_puertas      3
2  Ford Mustang       numero_puertas      5
3   Ford Fiesta       camara_trasera   True
4    Ford Focus       camara_trasera  False
5  Ford Mustang       camara_trasera   True
6   Ford Fiesta  sensor_aparcamiento   True
7    Ford Focus  sensor_aparcamiento  False
8  Ford Mustang  sensor_aparcamiento   True

# Conexión a PostgreSQL desde Python

conn = psycopg2.connect(host = "localhost", 
                        database = "nombre_BBDD",
                        user = "nombre_usuario", 
                        password = "contraseña_usuario")

In [106]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.8 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 6.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [107]:
import psycopg2 

conn = psycopg2.connect(host = "localhost", 
                        database = "db_movieStore",
                        user = "admin_movieStore", 
                        password = "123456")

In [108]:
sql_query = 'select * from film'
cursor = conn.cursor() # Creamos una variable con la que iniciamos el cursor
cursor.execute(sql_query) # Ejecutamos la query
rows = cursor.fetchall() # Creamos una variable con el restultado de la query en forma de lista de tuplas
tabla = pd.DataFrame(rows)# Genereamos un DataFrame a partir de la variable anterior
colnames = [desc[0] for desc in cursor.description] # Recuperamos los nombres de las columnas de la BBDD. cursor.description devuelve una tupla de tuplas con la misma longitud que columnas tenemos en nuestro resultado de la query. Además, el primer término de cada tupla es el nombre de la columna, por ello vamos a iterar por las tuplas y a tomar el término de la posición 0 para poder crear nuestra lista con los nombres de las columnas.
tabla = tabla.set_axis(colnames, axis = 1)# Renombramos las columnas del DF creado para que coincidan con las de la BBDD
display(tabla)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,2006-02-15 05:03:42,"[Deleted Scenes, Behind the Scenes]",'academi':1 'battl':15 'canadian':20 'dinosaur...
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,2006-02-15 05:03:42,"[Trailers, Deleted Scenes]",'ace':1 'administr':9 'ancient':19 'astound':4...
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,2006-02-15 05:03:42,"[Trailers, Deleted Scenes]",'adapt':1 'astound':4 'baloon':19 'car':11 'fa...
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,2006-02-15 05:03:42,"[Commentaries, Behind the Scenes]",'affair':1 'chase':14 'documentari':5 'fanci':...
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,2006-02-15 05:03:42,[Deleted Scenes],'african':1 'chef':11 'dentist':14 'documentar...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,2006-02-15 05:03:42,"[Trailers, Behind the Scenes]",'administr':12 'boat':8 'boy':17 'databas':11 ...
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,2006-02-15 05:03:42,"[Trailers, Behind the Scenes]",'boat':22 'cat':11 'challeng':14 'drama':5 'ki...
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,2006-02-15 05:03:42,[Deleted Scenes],'boy':16 'canadian':19 'compos':8 'core':2 'fa...
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,2006-02-15 05:03:42,"[Trailers, Deleted Scenes]",'ancient':19 'boat':11 'china':20 'discov':14 ...
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,2006-02-15 05:03:42,"[Trailers, Commentaries, Behind the Scenes]","'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona..."